import { Router, type IRouter } from "express";
import healthRouter from "./health";
import dashboardRouter from "./dashboard";
import eventsRouter from "./events";
import visitsRouter from "./visits";
import tasksRouter from "./tasks";
import risksRouter from "./risks";
import opsRoomRouter from "./ops-room";
import vipsRouter from "./vips";
import calendarRouter from "./calendar";
import invitationsRouter from "./invitations";
import guestsRouter from "./guests";
import participantsRouter from "./participants";
import rsvpRouter from "./rsvp";
import aiAssistantRouter from "./ai-assistant";
import reportsRouter from "./reports";
import dashboardProfilesRouter from "./dashboard-profiles";
import preferencesRouter from "./preferences";
import notificationsRouter from "./notifications";
import logisticsRouter from "./logistics";
import flightsRouter from "./flights";
import hotelsRouter from "./hotels";
import storageRouter from "./storage";
import referenceRouter from "./reference";
import contactsRouter from "./contacts";
import delegationsRouter from "./delegations";
import portraitsRouter from "./portraits";

const router: IRouter = Router();

router.use(healthRouter);
router.use(dashboardRouter);
router.use(eventsRouter);
router.use(visitsRouter);
router.use(tasksRouter);
router.use(risksRouter);
router.use(opsRoomRouter);
router.use(vipsRouter);
router.use(calendarRouter);
router.use(invitationsRouter);
router.use(guestsRouter);
router.use(participantsRouter);
router.use(rsvpRouter);
router.use(aiAssistantRouter);
router.use(reportsRouter);
router.use(dashboardProfilesRouter);
router.use(preferencesRouter);
router.use(notificationsRouter);
router.use(logisticsRouter);
router.use(flightsRouter);
router.use(hotelsRouter);
router.use(storageRouter);
router.use(referenceRouter);
router.use(contactsRouter);
router.use(delegationsRouter);
router.use(portraitsRouter);

export default router;
