import { palette } from "@/theme";
import {
  useListEventTravel, useCreateTravel, useUpdateTravel, useDeleteTravel, getListEventTravelQueryKey,
  useListEventHotelBookings, useCreateHotelBooking, useUpdateHotelBooking, useDeleteHotelBooking, getListEventHotelBookingsQueryKey,
  useListEventFleet, useCreateFleetAssignment, useUpdateFleetAssignment, useDeleteFleetAssignment, getListEventFleetQueryKey,
  useListEventGifts, useCreateGift, useUpdateGift, useDeleteGift, getListEventGiftsQueryKey,
  useListEventBudget, useCreateBudgetItem, useUpdateBudgetItem, useDeleteBudgetItem, getListEventBudgetQueryKey,
  useListEventDocuments, useCreateDocument, useUpdateDocument, useDeleteDocument, getListEventDocumentsQueryKey,
} from "@workspace/api-client-react";
import { Plane, BedDouble, Car, Gift, Wallet, FileText } from "lucide-react";
import type { SectionConfig } from "./section";

const C = palette;

/* eslint-disable @typescript-eslint/no-explicit-any */

export type LogisticsKey = "travel" | "hotel" | "fleet" | "gifts" | "budget" | "documents";

export const LOGISTICS_CONFIGS: Record<LogisticsKey, SectionConfig> = {
  travel: {
    base: "pages.commandCenter.logistics.travel",
    icon: Plane,
    color: C.calmTeal,
    statuses: ["scheduled", "confirmed", "arrived", "departed", "cancelled"],
    defaultStatus: "scheduled",
    statusOptKey: "st",
    primaryKey: "passengerName",
    primaryArKey: "passengerNameAr",
    fields: [
      { key: "direction", labelKey: "direction", type: "select", options: ["arrival", "departure"], optKey: "dir" },
      { key: "seatClass", labelKey: "seatClass", type: "select", options: ["first", "business", "economy"], optKey: "cls" },
      { key: "passengerNameAr", labelKey: "passengerAr", type: "text", dir: "rtl", half: true },
      { key: "passengerName", labelKey: "passengerEn", type: "text", dir: "ltr", required: true, half: true },
      { key: "flightNumber", labelKey: "flightNumber", type: "text", dir: "ltr", half: true },
      { key: "airline", labelKey: "airline", type: "text", half: true },
      { key: "origin", labelKey: "origin", type: "text", half: true },
      { key: "destination", labelKey: "destination", type: "text", half: true },
      { key: "departureTime", labelKey: "departureTime", type: "text", dir: "ltr", half: true },
      { key: "arrivalTime", labelKey: "arrivalTime", type: "text", dir: "ltr", half: true },
    ],
    display: [
      { key: "direction", labelKey: "direction", optKey: "dir" },
      { key: "flightNumber", labelKey: "flightNumber" },
      { key: "airline", labelKey: "airline" },
      { key: "origin", labelKey: "origin" },
      { key: "destination", labelKey: "destination" },
      { key: "seatClass", labelKey: "seatClass", optKey: "cls" },
      { key: "departureTime", labelKey: "departureTime" },
      { key: "arrivalTime", labelKey: "arrivalTime" },
    ],
    useList: useListEventTravel as any,
    listKey: getListEventTravelQueryKey,
    useCreate: useCreateTravel as any,
    useUpdate: useUpdateTravel as any,
    useDelete: useDeleteTravel as any,
  },
  hotel: {
    base: "pages.commandCenter.logistics.hotel",
    icon: BedDouble,
    color: C.mediumWood,
    statuses: ["reserved", "confirmed", "checkedIn", "checkedOut", "cancelled"],
    defaultStatus: "reserved",
    statusOptKey: "st",
    primaryKey: "guestName",
    primaryArKey: "guestNameAr",
    fields: [
      { key: "roomType", labelKey: "roomType", type: "select", options: ["presidential", "suite", "deluxe", "standard"], optKey: "room" },
      { key: "guestNameAr", labelKey: "guestAr", type: "text", dir: "rtl", half: true },
      { key: "guestName", labelKey: "guestEn", type: "text", dir: "ltr", required: true, half: true },
      { key: "hotelNameAr", labelKey: "hotelAr", type: "text", dir: "rtl", half: true },
      { key: "hotelName", labelKey: "hotelEn", type: "text", dir: "ltr", half: true },
      { key: "rooms", labelKey: "rooms", type: "number", half: true },
      { key: "confirmationNumber", labelKey: "confirmation", type: "text", dir: "ltr", half: true },
      { key: "checkIn", labelKey: "checkIn", type: "text", dir: "ltr", half: true },
      { key: "checkOut", labelKey: "checkOut", type: "text", dir: "ltr", half: true },
    ],
    display: [
      { key: "hotelName", arKey: "hotelNameAr", labelKey: "hotelEn" },
      { key: "roomType", labelKey: "roomType", optKey: "room" },
      { key: "rooms", labelKey: "rooms" },
      { key: "checkIn", labelKey: "checkIn" },
      { key: "checkOut", labelKey: "checkOut" },
      { key: "confirmationNumber", labelKey: "confirmation" },
    ],
    useList: useListEventHotelBookings as any,
    listKey: getListEventHotelBookingsQueryKey,
    useCreate: useCreateHotelBooking as any,
    useUpdate: useUpdateHotelBooking as any,
    useDelete: useDeleteHotelBooking as any,
  },
  fleet: {
    base: "pages.commandCenter.logistics.fleet",
    icon: Car,
    color: C.castleHill,
    statuses: ["assigned", "dispatched", "completed", "cancelled"],
    defaultStatus: "assigned",
    statusOptKey: "st",
    primaryKey: "assignedTo",
    primaryArKey: "assignedToAr",
    fields: [
      { key: "vehicleType", labelKey: "vehicleType", type: "select", options: ["sedan", "suv", "limousine", "van", "motorcade", "bus"], optKey: "veh" },
      { key: "assignedToAr", labelKey: "assignedAr", type: "text", dir: "rtl", half: true },
      { key: "assignedTo", labelKey: "assignedEn", type: "text", dir: "ltr", half: true },
      { key: "driverNameAr", labelKey: "driverAr", type: "text", dir: "rtl", half: true },
      { key: "driverName", labelKey: "driverEn", type: "text", dir: "ltr", half: true },
      { key: "plateNumber", labelKey: "plate", type: "text", dir: "ltr", half: true },
      { key: "capacity", labelKey: "capacity", type: "number", half: true },
      { key: "pickupLocation", labelKey: "pickup", type: "text", half: true },
      { key: "dropoffLocation", labelKey: "dropoff", type: "text", half: true },
      { key: "pickupTime", labelKey: "pickupTime", type: "text", dir: "ltr", half: true },
    ],
    display: [
      { key: "vehicleType", labelKey: "vehicleType", optKey: "veh" },
      { key: "driverName", arKey: "driverNameAr", labelKey: "driverEn" },
      { key: "plateNumber", labelKey: "plate" },
      { key: "capacity", labelKey: "capacity" },
      { key: "pickupLocation", labelKey: "pickup" },
      { key: "dropoffLocation", labelKey: "dropoff" },
      { key: "pickupTime", labelKey: "pickupTime" },
    ],
    useList: useListEventFleet as any,
    listKey: getListEventFleetQueryKey,
    useCreate: useCreateFleetAssignment as any,
    useUpdate: useUpdateFleetAssignment as any,
    useDelete: useDeleteFleetAssignment as any,
  },
  gifts: {
    base: "pages.commandCenter.logistics.gifts",
    icon: Gift,
    color: C.mangrove,
    statuses: ["planned", "approved", "procured", "delivered"],
    defaultStatus: "planned",
    statusOptKey: "st",
    primaryKey: "recipient",
    primaryArKey: "recipientAr",
    fields: [
      { key: "recipientAr", labelKey: "recipientAr", type: "text", dir: "rtl", half: true },
      { key: "recipient", labelKey: "recipientEn", type: "text", dir: "ltr", required: true, half: true },
      { key: "itemAr", labelKey: "itemAr", type: "text", dir: "rtl", half: true },
      { key: "item", labelKey: "itemEn", type: "text", dir: "ltr", half: true },
      { key: "quantity", labelKey: "quantity", type: "number", half: true },
      { key: "value", labelKey: "value", type: "number", half: true },
      { key: "currency", labelKey: "currency", type: "text", dir: "ltr", half: true },
      { key: "description", labelKey: "description", type: "text" },
    ],
    display: [
      { key: "item", arKey: "itemAr", labelKey: "itemEn" },
      { key: "quantity", labelKey: "quantity" },
      { key: "value", labelKey: "value", suffixKey: "currency" },
      { key: "description", labelKey: "description" },
    ],
    useList: useListEventGifts as any,
    listKey: getListEventGiftsQueryKey,
    useCreate: useCreateGift as any,
    useUpdate: useUpdateGift as any,
    useDelete: useDeleteGift as any,
  },
  budget: {
    base: "pages.commandCenter.logistics.budget",
    icon: Wallet,
    color: C.mediumWood,
    statuses: ["estimated", "approved", "committed", "paid"],
    defaultStatus: "estimated",
    statusOptKey: "st",
    primaryKey: "item",
    primaryArKey: "itemAr",
    fields: [
      { key: "category", labelKey: "category", type: "select", options: ["general", "travel", "hospitality", "security", "gifts", "media", "venue"], optKey: "cat" },
      { key: "itemAr", labelKey: "itemAr", type: "text", dir: "rtl", half: true },
      { key: "item", labelKey: "itemEn", type: "text", dir: "ltr", required: true, half: true },
      { key: "estimatedCost", labelKey: "estimated", type: "number", half: true },
      { key: "actualCost", labelKey: "actual", type: "number", half: true },
      { key: "currency", labelKey: "currency", type: "text", dir: "ltr", half: true },
      { key: "vendor", labelKey: "vendor", type: "text", half: true },
    ],
    display: [
      { key: "category", labelKey: "category", optKey: "cat" },
      { key: "estimatedCost", labelKey: "estimated", suffixKey: "currency" },
      { key: "actualCost", labelKey: "actual", suffixKey: "currency" },
      { key: "vendor", labelKey: "vendor" },
    ],
    useList: useListEventBudget as any,
    listKey: getListEventBudgetQueryKey,
    useCreate: useCreateBudgetItem as any,
    useUpdate: useUpdateBudgetItem as any,
    useDelete: useDeleteBudgetItem as any,
  },
  documents: {
    base: "pages.commandCenter.logistics.documents",
    icon: FileText,
    color: C.calmTeal,
    statuses: ["pending", "inReview", "approved", "signed", "archived"],
    defaultStatus: "pending",
    statusOptKey: "st",
    primaryKey: "title",
    primaryArKey: "titleAr",
    fields: [
      { key: "docType", labelKey: "docType", type: "select", options: ["general", "agenda", "briefing", "clearance", "contract", "itinerary"], optKey: "type" },
      { key: "titleAr", labelKey: "titleAr", type: "text", dir: "rtl", half: true },
      { key: "title", labelKey: "titleEn", type: "text", dir: "ltr", required: true, half: true },
      { key: "referenceNumber", labelKey: "reference", type: "text", dir: "ltr", half: true },
      { key: "owner", labelKey: "owner", type: "text", half: true },
      { key: "filePath", labelKey: "file", type: "file", nameKey: "fileName" },
      { key: "url", labelKey: "url", type: "text", dir: "ltr" },
    ],
    display: [
      { key: "docType", labelKey: "docType", optKey: "type" },
      { key: "referenceNumber", labelKey: "reference" },
      { key: "owner", labelKey: "owner" },
      { key: "filePath", labelKey: "file", isFile: true, nameKey: "fileName" },
      { key: "url", labelKey: "url", isLink: true },
    ],
    useList: useListEventDocuments as any,
    listKey: getListEventDocumentsQueryKey,
    useCreate: useCreateDocument as any,
    useUpdate: useUpdateDocument as any,
    useDelete: useDeleteDocument as any,
  },
};
